config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  root 'home#index'
  match 'search' => 'home#index', as: :search_home, via: [:get, :post]
  match 'search(/:id)' => 'members#show', as: :search_profile, via: [:get, :post]

  resources :members, only: [:create]

  get 'signup' => 'members#new', as: :signup
  get 'logout' => 'members#logout', as: :logout
  get 'profile(/:id)' => 'members#show', as: :profile
  get 'friends(/:id)' => 'members#friends', as: :friends
  get 'add_friend/:id' => 'members#add_friend', as: :add_friend
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :member
  belongs_to :friend, class_name: :Member

  validates :member_id, uniqueness: { scope: :friend_id }
end

app/models/member.rb
class Member < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  API_URL = 'https://api-ssl.bitly.com'

  validates :name, :original_url, presence: true
  validates :original_url, :short_url, url: true, allow_nil: true

  before_validation :retrieve_short_url
  after_create :store_headings

  has_many :friendships
  has_many :friends, class_name: :Member, through: :friendships

  def self.home_search(query, not_include)
    __elasticsearch__.search(
      query: {
        bool: {
          must: { match: { headings: query } },
          must_not: { match: { id: not_include } }
        }
      }, highlight: { fields: { headings: {} } }
    )
  end

  def self.profile_search(query, not_include, not_include2)
    __elasticsearch__.search(
      query: {
        bool: {
          must: { match: { headings: query } },
          must_not: { match: { id: not_include } },
          must_not: { match: { id: not_include2 } }
        }
      }, highlight: { fields: { headings: {} } }
    )
  end

  def first_name
    name.split(' ').first
  end

  def not_friend_yet(member_id)
    friendships.none? { |f| f.friend_id == member_id }
  end

  private

  def retrieve_short_url
    response = JSON.parse(RestClient.get("#{API_URL}/v3/shorten?access_token=#{BITLY_TOKEN}&longUrl=#{original_url}"))
    if response['status_code'] != 200
      errors.add(:short_url, "is invalid. Error: #{response['status_txt']}")
      return false
    end
    self.short_url = response['data']['url']
  end

  def store_headings
    StoreHeadingsJob.perform_later(id)
  end
end

app/models/short_path.rb
class ShortPath
  def self.get_path(from, to)
    @original_from = from
    @visited = [from]
    @i = 0
    @a = []
    @path = {}
    find_friend(from, to)
    @path.min_by { |_, v| v.size }[1] if @path.any?
  end

  def self.find_friend(from, to)
    if from.friendships.any? { |f| f.friend_id == to.id }
      @a.unshift(@original_from.id)
      @a.push(to.id)

      @path[@i] = @a
      @a = []
      @i += 1
    else
      @visited.push(from.id)
      from.friendships.each do |friendship|
        next if @visited.include?(friendship.friend_id) || (@a == [] && from != @original_from)
        @a.push(friendship.friend_id)
        find_friend(friendship.friend, to)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :verify_authentication
  helper_method :current_member, :random_color, :logged_in?

  def random_color
    Random.new.bytes(3).unpack('H*').first
  end

  def log_in(member)
    session[:member_id] = member.id
  end

  def logged_in?
    current_member.present?
  end

  def log_out
    session.delete(:member_id) if session[:member_id]
  end

  def current_member
    @current_member ||= Member.find_by(id: session[:member_id]) if session[:member_id]
  end

  private

  def verify_authentication
    redirect_to signup_path, alert: 'You must sign up to access this page' unless logged_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    query = params[:search].presence && params[:search][:query]
    if query
      @members = Member.home_search(query, current_member.id)
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  skip_before_action :verify_authentication, only: [:new, :create]
  before_action :set_member, only: [:show, :friends, :add_friend]

  # GET /members/1
  # GET /members/1.json
  def show
    query = params[:search].presence && params[:search][:query]
    if query
      @members = Member.profile_search(query, current_member.id, @member.id)
    end
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  def friends
  end

  def add_friend
    current_member.friendships.create(friend_id: @member.id)
    @member.friendships.create(friend_id: current_member.id)
    redirect_to profile_path(@member), notice: "You and #{@member.first_name} are now friends."
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    if @member.save
      log_in(@member)
      redirect_to root_path, notice: "Hi #{@member.name}, nice to see you here."
    else
      render :new
    end
  end

  def logout
    log_out if logged_in?
    redirect_to signup_path, notice: 'Bye, see you soon.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      id = params[:id].present? ? params[:id] : session[:member_id]
      @member = Member.find(id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def short_path_breadcrumb(from, to)
    text = []
    from = Member.find(from)
    to = Member.find(to)
    path = ShortPath.get_path(from, to)

    if path
      path.each do |member_id|
        member = Member.find(member_id)
        text << link_to(member.name, profile_path(member))
      end

      return text.join(' > ').html_safe
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/index.html.erb
<%= render 'layouts/messages' %>

<%= render partial: 'shared/search', locals: { url: search_home_path } %>

<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Recent headings</h6>
  <% Member.last(5).each do |member| %>
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Recent heading"><title>Recent heading</title><rect width="100%" height="100%" fill="#<%= random_color %>"></rect></svg>
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark"><%= link_to member.name, profile_path(member) %></strong>
        <%= member.headings&.truncate(170, omission: '...') %>
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<div class="alert" role="alert" style="display: none;" id="alert">
  <button type="button" class="close" onclick="$(this).parent().fadeOut();">&times;</button>
  <span></span>
</div>
<% if defined?(object) && object && object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li> <small> <%= message %> </small> </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <% flash.each do |name, msg| %>
    <%- next if name.to_s == 'timedout' || !msg.present? %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, content_tag(:small, msg.html_safe), :id => "flash_#{name}" %>
      </div>
    <% elsif msg.is_a?(Array) && msg.any? %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>
          <% msg.each do |message| %>
            <li> <small> <%= message %> </small> </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% flash.discard(name) %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rapport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <div class="nav-scroller bg-white shadow-sm">
      <nav class="nav nav-underline">
        <%= link_to root_path, class: 'nav-link active' do %><i class="rapport-small-icon">R</i> <span class="rapport-brand-name">Rapport</span><% end %>
        <% if logged_in? %>
          <%= link_to profile_path, class: "nav-link" do %>Profile<% end %>
          <%= link_to friends_path, class: "nav-link" do %>Friends <span class="badge badge-pill bg-light align-text-bottom"><%= current_member.friendships.count %></span><% end %>
          <div class="divider mr-auto"></div>
          <%= link_to 'Log out', logout_path, class: 'nav-link' %>
        <% else %>
          <div class="divider mr-auto"></div>
          <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
        <% end %>
      </nav>
    </div>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true, html: { class: 'form-signin' }) do |form| %>

  <div class="brand text-center">
    <i class="rapport-icon">R</i>
  </div>

  <%= render 'layouts/messages', object: member %>

  <div class="form-label-group">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
    <%= form.label :name %>
  </div>

  <div class="form-label-group">
    <%= form.text_field :original_url, class: 'form-control', placeholder: 'Name' %>
    <%= form.label :original_url, 'Site URL' %>
  </div>

  <div class="actions">
    <%= form.submit 'Sign up', class: "btn btn-lg btn-danger btn-block" %>
  </div>
<% end %>

app/views/members/_friends.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0"><%= member.first_name %>'s friends</h6>

  <% unless member.friends.any? %>
    <small class="d-block mt-3">
      <div class="alert alert-info"><%= member.first_name %> does not have any friends yet.</div>
    </small>
  <% end %>

  <% member.friends.each do |friend| %>
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Friend photo"><title>Friend photo</title><rect width="100%" height="100%" fill="#<%= random_color %>"></rect></svg>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark"><%= friend.name %></strong>
          <%= link_to profile_path(friend) do %>Profile<% end %>
        </div>
        <span class="d-block"><%= link_to friend.original_url, friend.original_url, target: '_blank' %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/members/friends.html.erb
<%= render partial: 'friends', locals: { member: @member } %>

app/views/members/new.html.erb
<%= render 'form', member: @member %>

app/views/members/show.html.erb
<%= render 'layouts/messages', object: @member %>

<div class="d-flex align-items-center p-3 my-3 rounded shadow-sm">
  <svg class="bd-placeholder-img mr-2 rounded" width="48" height="48" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Member photo"><title>Member photo</title><rect width="100%" height="100%" fill="#<%= random_color %>"></rect></svg>
  <div class="lh-100 mr-auto">
    <h6 class="mb-0 lh-100"><%= @member.name %> <small><%= "#{@member.friendships.count} #{'friend'.pluralize(@member.friendships.count)}" %></small></h6>
    <small><%= link_to @member.short_url, @member.short_url, target: '_blank' %></small><br>
  </div>
  <% if @member.id != current_member.id %>
    <% if current_member.not_friend_yet(@member.id) %>
      <%= link_to add_friend_path(@member), class: 'btn btn-outline-danger' do %>Add friend<% end %>
    <% else %>
      <span class="btn btn-outline-secondary">Your friend</span>
    <% end %>
  <% end %>
  </div>
</div>

<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Headings</h6>
  <div class="media text-muted pt-3">
    <p class="media-body pb-3 mb-0 small lh-125">
      <%= @member.headings %>
    </p>
  </div>
</div>

<%= render partial: 'shared/search', locals: { url: search_profile_path(@member) } %>

<%= render partial: 'friends', locals: { member: @member } %>

app/views/shared/_search.html.erb
<%= form_for :search, url: url do |f| %>
  <div class="form-label-group">
    <%= f.text_field :query, value: params[:search].presence && params[:search][:query], class: 'form-control', placeholder: 'Search' %>
    <%= f.label :query, 'Search' %>
  </div>
<% end %>

<% if params[:search] && params[:search][:query].present? %>
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Search results</h6>
    <% unless @members.any? %>
      <small class="d-block mt-3">
        <div class="alert alert-info">Your search did not return any data.</div>
      </small>
    <% end %>
    <% @members&.each do |member| %>
      <div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Recent heading"><title>Recent heading</title><rect width="100%" height="100%" fill="#<%= random_color %>"></rect></svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark"><%= link_to member.name, profile_path(member.id) %></strong>
          <%= member.highlight.headings.join(' ').html_safe %>
          <% from = @member.present? ? @member : current_member %>
          <br><br>
          <span class="custom_breadcrumb">  <%= short_path_breadcrumb(from.id, member._id) %></span>
        </p>
      </div>
    <% end %>
  </div>
<% end %>